const acceptedData = {
  media_type: [
    'online',
    'direct mail',
    'infomercial',
    'outbound call',
  ],
  media_channel: [
    'facebook',
    'youtube',
    'search',
    'display',
    'linkedin',
    'local',
    'sms',
    'instagram',
    'pinterest',
    'native',
    'email',
  ],
  asset_type: [
    'Reg Page',
    'Promo Page',
    'Thank You Page',
    'Brand Site',
    'Squeeze Page',
    'Compliance Page',
    'Video',
    'Ad Creative',
  ],
  platform_type: [
    'wordpress',
    'instapage',
    'static html',
    'nodejs',
    'python',
    'ruby',
    'php',
  ],
  property_type: [
    'reg page',
    'promo page',
    'thank you page',
    'brand site',
    'squeeze page',
    'compliance page',
    'video',
    'ad creative',
    'landing page'
  ],
  draw_name: [
    'andrew cordle',
    'barbara corcoran',
    'bnb',
    'bryan baeumler',
    'dallas robinson',
    'dean graziosi',
    'desert flippers',
    'doug clark',
    'good bones',
    'jessie and tina',
    'josh altman',
    'kevin oleary',
    'renovate to rent',
    'robert herjavec',
    'sean conlon',
    'snap flip',
    'scott yancey',
    'tomi lahren',
    'womens night out',
  ],
};

module.exports = acceptedData;
